export type FirstLegTransportMethod = "海卡" | "海派" | "空卡" | "空派" | "铁路" | "快递" | "卡航";
export type BillingMethod = "计费重" | "实重" | "体积";
export type TaxMethod = "报税" | "不报税";
export type CarrierStatus = "启用" | "停用";
export type CarrierCurrency = "RMB" | "USD" | "IDR";

export interface FirstLegCarrier {
  id: string;
  carrierCode: string;
  carrierName: string;
  carrierShortName?: string;
  countryOrRegion: "中国" | "印尼" | "美国" | "其他";
  city?: string;
  carrierLevel?: "A级" | "B级" | "C级";
  contactName: string;
  contactPhone: string;
  email?: string;
  wechat?: string;
  address?: string;
  settlementCurrency: CarrierCurrency;
  paymentMethod: "月结" | "票结" | "预付" | "到付";
  accountPeriodDays?: number;
  invoiceInfo?: string;
  bankAccount?: string;
  payeeName?: string;
  supportedTransportMethods?: FirstLegTransportMethod[];
  supportedDestinations?: string[];
  supportTaxDeclaration?: boolean;
  supportCustomsClearance?: boolean;
  supportDelivery?: boolean;
  status: CarrierStatus;
  channelCount: number;
  remark?: string;
  createdBy?: string;
  createdAt?: string;
  updatedBy?: string;
  updatedAt?: string;
}

export interface FirstLegCarrierChannel {
  id: string;
  carrierId: string;
  carrierName: string;
  channelCode: string;
  channelName: string;
  transportMethod: FirstLegTransportMethod;
  estimatedTransitDays: number;
  minTransitDays?: number;
  maxTransitDays?: number;
  cutoffTime?: string;
  departureFrequency?: string;
  billingMethod: BillingMethod;
  chargeWeightFactor?: number;
  volumeDivisor?: number;
  minChargeWeight?: number;
  firstWeightPrice?: number;
  additionalWeightPrice?: number;
  unitPrice?: number;
  feeCurrency: CarrierCurrency;
  taxMethod: TaxMethod;
  includeTax?: boolean;
  includeCustomsClearance?: boolean;
  includeDelivery?: boolean;
  taxRemark?: string;
  originPlace?: string;
  destinationCountry: string;
  destinationWarehouse?: string;
  applicableArea?: string;
  transferCenter?: string;
  supportBattery?: boolean;
  supportLiquid?: boolean;
  supportSensitiveGoods?: boolean;
  supportNormalGoods?: boolean;
  maxBoxWeight?: number;
  maxBoxVolume?: number;
  status: CarrierStatus;
  remark?: string;
  createdBy?: string;
  createdAt?: string;
  updatedBy?: string;
  updatedAt?: string;
}
