import { useMemo, useState } from "react";
import { Download, Search, SlidersHorizontal } from "lucide-react";
import DesignLogicCard from "../../components/common/DesignLogicCard";
import FormModal from "../../components/common/FormModal";
import PageHeader from "../../components/common/PageHeader";
import Toast from "../../components/common/Toast";

type Row={id:string;sku:string;name:string;type:string;supplier:string;qty:number;unit:string;purchase:number;domestic:number;firstLeg:number;port:number;lastMile:number|null;duty:number;vat:number;clearance:number;other:number;adjustment:number;saleTarget:string;currency:string;saleAmount:number|null;incomeStatus:string;confirmedIncome:number;costComplete:boolean;allocation:string;firstLegNo:string};
const initialRows:Row[]=[
  {id:"ID-MP-2026-0001",sku:"FAB-5000",name:"180g纯棉针织布",type:"面料",supplier:"广州华盛面料有限公司",qty:10000,unit:"米",purchase:100000,domestic:2000,firstLeg:8000,port:3000,lastMile:1500,duty:3600,vat:1800,clearance:1600,other:500,adjustment:0,saleTarget:"PT CM",currency:"CNY",saleAmount:130000,incomeStatus:"待确认",confirmedIncome:0,costComplete:true,allocation:"已分摊",firstLegNo:"TB-2026-0001"},
  {id:"ID-MP-2026-0002",sku:"ACC-2002",name:"白色纽扣",type:"辅料",supplier:"东莞宏远辅料有限公司",qty:50000,unit:"个",purchase:20000,domestic:800,firstLeg:2000,port:900,lastMile:null,duty:700,vat:300,clearance:500,other:0,adjustment:0,saleTarget:"GOTO",currency:"CNY",saleAmount:null,incomeStatus:"待确认",confirmedIncome:0,costComplete:false,allocation:"部分分摊",firstLegNo:"TB-2026-0002"},
  {id:"EQ-PO-2026-0001",sku:"EQ-SEW-001",name:"工业平缝机",type:"机器设备",supplier:"深圳设备供应商",qty:20,unit:"台",purchase:160000,domestic:3000,firstLeg:12000,port:4000,lastMile:2000,duty:8000,vat:4000,clearance:2500,other:0,adjustment:0,saleTarget:"FADFAD",currency:"CNY",saleAmount:215000,incomeStatus:"未确认",confirmedIncome:0,costComplete:true,allocation:"已分摊",firstLegNo:"TB-2026-0003"},
];
const money=(n:number|null)=>n===null?"未录入":n.toLocaleString("zh-CN",{minimumFractionDigits:2,maximumFractionDigits:2});
const total=(r:Row)=>r.purchase+r.domestic+r.firstLeg+r.port+(r.lastMile??0)+r.duty+r.vat+r.clearance+r.other+r.adjustment;
const tag=(text:string,ok=false)=><span className={`rounded-full px-2 py-1 ${ok?'bg-emerald-50 text-emerald-700':text.includes('不完整')||text.includes('缺失')||text.includes('未分摊')?'bg-red-50 text-red-700':'bg-amber-50 text-amber-700'}`}>{text}</span>;

export default function SubjectOperatingDetail(){
  const [rows,setRows]=useState(initialRows); const [keyword,setKeyword]=useState(""); const [type,setType]=useState("全部"); const [target,setTarget]=useState("全部"); const [detail,setDetail]=useState<Row|null>(null); const [editing,setEditing]=useState<Row|null>(null); const [allocating,setAllocating]=useState<Row|null>(null); const [saleAmount,setSaleAmount]=useState(""); const [allocationMode,setAllocationMode]=useState("按重量分摊"); const [manualAllocation,setManualAllocation]=useState("8000"); const [toast,setToast]=useState("");
  const filtered=useMemo(()=>rows.filter(r=>(!keyword||[r.id,r.sku,r.name,r.supplier,r.firstLegNo].join(" ").includes(keyword))&&(type==="全部"||r.type===type)&&(target==="全部"||r.saleTarget===target)),[rows,keyword,type,target]);
  const summary=useMemo(()=>{const purchase=filtered.reduce((s,r)=>s+r.purchase,0),freight=filtered.reduce((s,r)=>s+r.domestic+r.firstLeg+r.port+(r.lastMile??0),0),tax=filtered.reduce((s,r)=>s+r.duty+r.vat+r.clearance,0),cost=filtered.reduce((s,r)=>s+total(r),0),sales=filtered.reduce((s,r)=>s+(r.saleAmount??0),0),confirmed=filtered.reduce((s,r)=>s+r.confirmedIncome,0),gross=sales-cost;return {purchase,freight,tax,cost,sales,confirmed,gross,rate:sales?gross/sales*100:0,missing:filtered.filter(r=>!r.costComplete||r.saleAmount===null).length}},[filtered]);
  const openEdit=(r:Row)=>{setEditing(r);setSaleAmount(String(r.saleAmount??""))}; const saveSale=()=>{if(!editing)return;setRows(x=>x.map(r=>r.id===editing.id?{...r,saleAmount:saleAmount===""?null:Number(saleAmount)}:r));setEditing(null);setToast("销售金额已更新，毛利与毛利率已重新计算")};
  const cards=[["采购总金额",summary.purchase],["运费总金额",summary.freight],["税费总金额",summary.tax],["总成本",summary.cost],["销售总金额",summary.sales],["已确认收入",summary.confirmed],["毛利",summary.gross],["毛利率",`${summary.rate.toFixed(2)}%`],["数据缺失数量",`${summary.missing} 条`]];
  return <div><PageHeader title="主体经营明细" desc="供老板和财务查看香港公司维度的采购、完整成本、销售、收入与毛利数据。" extra={<span className="rounded bg-violet-50 px-3 py-1.5 text-xs text-violet-700">权限 Demo：老板 / 财务可见</span>}/>
    <section className="mb-3 grid gap-2 sm:grid-cols-2 lg:grid-cols-3 xl:grid-cols-9">{cards.map(([label,value])=><div key={String(label)} className="rounded border bg-white p-3"><div className="text-xs text-gray-500">{label}</div><div className={`mt-1 text-lg font-semibold ${label==='毛利'&&Number(value)<0?'text-red-600':label==='数据缺失数量'?'text-amber-600':'text-gray-900'}`}>{typeof value==='number'?money(value):value}</div>{label!=='毛利率'&&label!=='数据缺失数量'&&<div className="text-[10px] text-gray-400">CNY</div>}</div>)}</section>
    <section className="mb-3 rounded border bg-white p-3"><div className="grid gap-2 md:grid-cols-3 xl:grid-cols-7"><select className="h-8 rounded border px-2 text-sm"><option>HiGOOD 香港公司</option></select><select className="h-8 rounded border px-2 text-sm" value={type} onChange={e=>setType(e.target.value)}>{["全部","面料","辅料","办公耗材","机器设备","固定资产"].map(x=><option key={x}>{x}</option>)}</select><input className="h-8 rounded border px-2 text-sm" placeholder="采购单号 / SKU / 物料 / 物流单" value={keyword} onChange={e=>setKeyword(e.target.value)}/><select className="h-8 rounded border px-2 text-sm" value={target} onChange={e=>setTarget(e.target.value)}>{["全部","PT CM","GOTO","FADFAD","印尼车缝工厂 A"].map(x=><option key={x}>{x}</option>)}</select>{["收入状态","成本是否完整","销售金额是否录入"].map(x=><select key={x} className="h-8 rounded border px-2 text-sm"><option>{x}</option><option>全部</option></select>)}</div><div className="mt-3 flex flex-wrap gap-2"><button className="inline-flex h-8 items-center gap-1 rounded bg-blue-600 px-3 text-sm text-white"><Search size={14}/>查询</button><button className="h-8 rounded border px-3 text-sm" onClick={()=>{setKeyword("");setType("全部");setTarget("全部")}}>重置</button><button className="inline-flex h-8 items-center gap-1 rounded border px-3 text-sm"><Download size={14}/>导出</button><button className="inline-flex h-8 items-center gap-1 rounded bg-emerald-600 px-3 text-sm text-white" onClick={()=>filtered[0]&&setAllocating(filtered[0])}><SlidersHorizontal size={14}/>批量分摊费用</button><button className="h-8 rounded border border-violet-200 bg-violet-50 px-3 text-sm text-violet-700" onClick={()=>setToast("已批量进入收入状态编辑 Demo")}>批量编辑收入状态</button></div></section>
    <section className="overflow-x-auto border bg-white"><table className="min-w-[3600px] text-left text-xs"><thead className="bg-gray-50"><tr>{["采购单号","SKU","物料名称","物料类型","采购主体","国内供应商","采购数量","基础单位","采购成本","国内段运费","头程 / 海运费","目的港费用","末端配送费","关税","增值税","清关费","其他费用","调整金额","总成本","销售对象","销售币种","销售金额","收入状态","已确认收入","毛利","毛利率","成本是否完整","销售金额是否录入","分摊状态","操作"].map(x=><th key={x} className="whitespace-nowrap border-b px-2 py-2 font-medium">{x}</th>)}</tr></thead><tbody>{filtered.map(r=>{const cost=total(r),gross=r.saleAmount===null?null:r.saleAmount-cost;return <tr key={r.id} className="border-b hover:bg-blue-50/30">{[r.id,r.sku,r.name,r.type,"HiGOOD 香港公司",r.supplier,money(r.qty),r.unit,money(r.purchase),money(r.domestic),money(r.firstLeg),money(r.port),money(r.lastMile),money(r.duty),money(r.vat),money(r.clearance),money(r.other),money(r.adjustment),money(cost),r.saleTarget,r.currency,money(r.saleAmount)].map((x,i)=><td key={i} className={`whitespace-nowrap px-2 py-3 ${i===0||i===1?'font-medium text-blue-600':''}`}>{x}</td>)}<td className="px-2 py-3">{tag(r.incomeStatus,r.incomeStatus==='已确认'||r.incomeStatus==='已收款')}</td><td className="px-2 py-3 text-right">{money(r.confirmedIncome)}</td><td className="px-2 py-3 text-right font-medium">{money(gross)}</td><td className="px-2 py-3 text-right">{gross===null||!r.saleAmount?'-':`${(gross/r.saleAmount*100).toFixed(2)}%`}</td><td className="px-2 py-3">{tag(r.costComplete?'成本完整':'成本不完整',r.costComplete)}</td><td className="px-2 py-3">{tag(r.saleAmount===null?'销售金额缺失':'销售金额已录入',r.saleAmount!==null)}</td><td className="px-2 py-3">{tag(r.allocation,r.allocation==='已分摊')}</td><td className="whitespace-nowrap px-2 py-3"><button className="mr-3 text-blue-600" onClick={()=>setDetail(r)}>查看明细</button><button className="mr-3 text-blue-600" onClick={()=>openEdit(r)}>编辑销售金额</button><button className="mr-3 text-emerald-600" onClick={()=>setAllocating(r)}>成本分摊</button><button className="mr-3 text-gray-600">查看采购单</button><button className="mr-3 text-gray-600">查看物流费用</button><button className="text-gray-600">操作日志</button></td></tr>})}</tbody></table></section>
    <DesignLogicCard sections={[{title:"页面功能说明",headers:["说明"],rows:[["主体经营明细用于给老板和财务查看香港公司维度的采购、成本、费用、销售、收入和毛利情况。系统不做固定贸易链路配置，也不限制某类物料必须销售给某个主体。销售对象和销售金额直接在采购单中手动维护，所有运费、税费、清关费和其他费用均计入香港公司成本。收入确认节点暂时待定，页面仅展示收入状态，不做强制流转。"]]},{title:"业务逻辑说明",headers:["业务场景","规则说明","页面结果"],rows:[["不做贸易链路配置","销售对象不固定，不能通过配置写死","不新增贸易链路配置模块"],["销售对象维护","销售对象直接在采购单中选择","读取采购单最终销售对象"],["销售金额维护","销售金额在采购单中手动录入","不新增香港公司销售单"],["FADFAD","FADFAD 就是供应链平台","系统只维护一个主体"],["成本范围","所有费用都计入香港公司成本","总成本包含采购、运费、税费和清关费"],["费用分摊","支持金额、重量、体积、手动分摊","财务可调整最终分摊金额"],["数据缺失","成本、销售、收入缺失均标记","财务可筛选待补数据"],["毛利核算","毛利 = 销售金额 - 总成本","销售金额缺失时毛利为空"],["查看角色","老板和财务查看经营明细","查看采购、成本、销售、收入、毛利全维度"]]}]} />

    <FormModal open={!!detail} onClose={()=>setDetail(null)} title="主体经营明细详情" widthClass="w-[1100px]">{detail&&<div className="max-h-[72vh] space-y-3 overflow-y-auto pr-1 text-xs"><Info title="一、采购基础信息" items={[["采购单号",detail.id],["SKU",detail.sku],["物料名称",detail.name],["物料类型",detail.type],["国内供应商",detail.supplier],["采购数量",`${money(detail.qty)} ${detail.unit}`],["采购时间","2026-07-28 10:30"],["采购员","王采购"]]}/><Info title="二、贸易与销售信息" items={[["采购主体","HiGOOD 香港公司"],["出口主体","HiGOOD 香港公司"],["销售对象",detail.saleTarget],["销售币种",detail.currency],["销售单价",detail.saleAmount?money(detail.saleAmount/detail.qty):"未录入"],["销售金额",money(detail.saleAmount)],["销售备注","按真实业务手动维护"],["录入人 / 时间","财务管理员 / 2026-08-06 10:20"]]}/><CostTable row={detail}/><Info title="四、费用分摊明细" items={[["头程 / 海运费",`${detail.firstLegNo} · 按重量 · 最终 ${money(detail.firstLeg)}`],["目的港费用",`${detail.firstLegNo} · 手动分摊 · 最终 ${money(detail.port)}`],["关税",`TAX-2026-0001 · 按金额 · 最终 ${money(detail.duty)}`]]}/><Info title="五、收入信息" items={[["收入状态",detail.incomeStatus],["已确认收入",money(detail.confirmedIncome)],["收入确认时间","-"],["收款状态","未收款"],["收款金额","0.00"],["收款备注","收入确认节点待定"]]}/><Info title="六、毛利核算" items={[["总成本",money(total(detail))],["销售金额",money(detail.saleAmount)],["毛利",detail.saleAmount===null?"-":money(detail.saleAmount-total(detail))],["毛利率",detail.saleAmount?`${((detail.saleAmount-total(detail))/detail.saleAmount*100).toFixed(2)}%`:"-"]]}/><div className="rounded border border-amber-200 bg-amber-50 p-3"><b>七、数据缺失提醒</b><div className="mt-2">{[detail.saleAmount===null&&"销售金额未录入",!detail.costComplete&&"末端配送费未确认",detail.allocation!=="已分摊"&&"部分费用未完成分摊",detail.incomeStatus.includes("确认")&&"收入状态待确认"].filter(Boolean).join("；")||"当前记录数据完整"}</div></div><Info title="八、操作日志" items={[["2026-08-06 10:20","财务管理员查看经营明细"],["2026-08-05 16:30","系统汇总采购及费用数据"]]}/></div>}</FormModal>
    <FormModal open={!!editing} onClose={()=>setEditing(null)} title="编辑销售金额" widthClass="w-[620px]">{editing&&<div className="space-y-3 text-sm"><Info title="采购信息" items={[["采购单号",editing.id],["SKU",editing.sku],["物料名称",editing.name],["当前销售对象",editing.saleTarget]]}/><div className="grid grid-cols-2 gap-3"><label className="grid gap-1 text-xs text-gray-500">销售币种<select className="h-8 rounded border px-2"><option>CNY</option><option>USD</option><option>IDR</option></select></label><label className="grid gap-1 text-xs text-gray-500">销售单价<input className="h-8 rounded border px-2" defaultValue={editing.saleAmount?editing.saleAmount/editing.qty:""}/></label><label className="grid gap-1 text-xs text-gray-500">销售金额<input className="h-8 rounded border px-2" type="number" value={saleAmount} onChange={e=>setSaleAmount(e.target.value)}/></label><label className="grid gap-1 text-xs text-gray-500">销售备注<input className="h-8 rounded border px-2" defaultValue="财务手动确认"/></label></div><div className="flex justify-end gap-2 border-t pt-3"><button className="h-8 rounded border px-4" onClick={()=>setEditing(null)}>取消</button><button className="h-8 rounded bg-blue-600 px-4 text-white" onClick={saveSale}>保存</button></div></div>}</FormModal>
    <FormModal open={!!allocating} onClose={()=>setAllocating(null)} title="费用分摊" widthClass="w-[760px]">{allocating&&<div className="space-y-3 text-sm"><div className="grid grid-cols-2 gap-3"><Field label="费用来源单号" value={allocating.firstLegNo}/><Field label="费用类型" value="头程 / 海运费"/><Field label="费用总金额" value="22,000.00"/><Field label="币种" value="CNY"/><Field label="关联采购单" value={allocating.id}/><Field label="关联 SKU" value={allocating.sku}/><label className="grid gap-1 text-xs text-gray-500">分摊方式<select className="h-8 rounded border px-2" value={allocationMode} onChange={e=>setAllocationMode(e.target.value)}>{["按金额分摊","按重量分摊","按体积分摊","手动分摊"].map(x=><option key={x}>{x}</option>)}</select></label><Field label="系统建议分摊金额" value="7,800.00"/><label className="grid gap-1 text-xs text-gray-500">手动调整金额<input className="h-8 rounded border px-2" value={manualAllocation} onChange={e=>setManualAllocation(e.target.value)}/></label><Field label="最终分摊金额" value={money(Number(manualAllocation||0))}/><label className="col-span-2 grid gap-1 text-xs text-gray-500">分摊备注<textarea className="h-16 rounded border px-2 py-1" defaultValue="系统建议值允许财务手动调整，最终金额以人工确认值为准。"/></label></div><div className="flex justify-end gap-2 border-t pt-3"><button className="h-8 rounded border px-4" onClick={()=>setAllocating(null)}>取消</button><button className="h-8 rounded bg-emerald-600 px-4 text-white" onClick={()=>{setAllocating(null);setToast(`已按${allocationMode}保存最终分摊金额`)}}>保存分摊</button></div></div>}</FormModal><Toast msg={toast}/>
  </div>;
}

function Field({label,value}:{label:string;value:string}){return <label className="grid gap-1 text-xs text-gray-500">{label}<div className="h-8 rounded border bg-gray-50 px-2 leading-8 text-gray-800">{value}</div></label>}
function Info({title,items}:{title:string;items:string[][]}){return <section className="rounded border p-3"><h3 className="mb-2 text-sm font-semibold">{title}</h3><div className="grid gap-2 md:grid-cols-4">{items.map(([label,value])=><div key={label}><span className="text-gray-500">{label}</span><div className="mt-1 font-medium">{value}</div></div>)}</div></section>}
function CostTable({row}:{row:Row}){const items=[["采购成本",row.purchase,"面辅料采购单","是"],["国内段运费",row.domestic,"面辅料采购对账","是"],["头程 / 海运费",row.firstLeg,"头程物流单","是"],["目的港费用",row.port,"物流费用对账","是"],["末端配送费",row.lastMile,"手动录入",row.lastMile===null?"否":"是"],["关税",row.duty,"清关信息","是"],["增值税",row.vat,"清关信息","是"],["清关费",row.clearance,"清关信息","是"],["其他费用",row.other,"手动录入","是"],["调整金额",row.adjustment,"财务调整","是"],["总成本",total(row),"自动汇总","-"]] as const;return <section className="rounded border p-3"><h3 className="mb-2 text-sm font-semibold">三、成本明细</h3><table className="w-full text-left"><thead className="bg-gray-50"><tr>{["成本项","金额","来源单据","是否已确认"].map(x=><th key={x} className="border-b px-2 py-2">{x}</th>)}</tr></thead><tbody>{items.map(x=><tr key={x[0]} className="border-b last:border-0"><td className="px-2 py-2">{x[0]}</td><td className="px-2 py-2 text-right">{money(x[1])}</td><td className="px-2 py-2">{x[2]}</td><td className="px-2 py-2">{x[3]}</td></tr>)}</tbody></table></section>}
